from __future__ import annotations

import locale

LANGUAGES = {"pt": "Português", "en": "English", "es": "Español", "zh": "中文", "ru": "Русский", "ja": "日本語"}

TRANSLATIONS = {
"pt":{"title":"Golden Pot v0.1.1 — Comparador de pastas","subtitle":"Compare duas pastas com segurança. A versão 0.1 é somente leitura.","language":"Idioma","base_folder":"Pasta base","comparison_folder":"Pasta de comparação","report_destination":"Destino dos relatórios","configuration":"Configuração (opcional)","select_folder":"Selecionar pasta","select_file":"Selecionar arquivo","analyze":"Analisar pastas","ready":"Pronto. Nenhum arquivo será modificado.","select_config":"Selecionar configuração do Golden Pot","json_files":"Arquivos JSON","all_files":"Todos os arquivos","missing_title":"Informações ausentes","missing_message":"Selecione as três pastas.","analyzing":"Analisando as pastas...","failed":"A análise falhou.","completed":"Análise concluída com sucesso.","finished":"Concluído. As pastas originais não foram alteradas.","json_report":"Relatório JSON","text_report":"Relatório de texto","ADDED":"ADICIONADOS","UNCHANGED":"INALTERADOS","MODIFIED":"MODIFICADOS","PRESERVED":"PRESERVADOS","PROTECTED":"PROTEGIDOS","ERROR":"ERROS","TOTAL":"TOTAL"},
"en":{"title":"Golden Pot v0.1.1 — Folder Comparator","subtitle":"Compare any two folders safely. Version 0.1 is read-only.","language":"Language","base_folder":"Base folder","comparison_folder":"Comparison folder","report_destination":"Report destination","configuration":"Configuration (optional)","select_folder":"Select folder","select_file":"Select file","analyze":"Analyze folders","ready":"Ready. No files will be modified.","select_config":"Select Golden Pot configuration","json_files":"JSON files","all_files":"All files","missing_title":"Missing information","missing_message":"Select all three folders.","analyzing":"Analyzing folders...","failed":"Analysis failed.","completed":"Analysis completed successfully.","finished":"Finished. Original folders were not changed.","json_report":"JSON report","text_report":"Text report","ADDED":"ADDED","UNCHANGED":"UNCHANGED","MODIFIED":"MODIFIED","PRESERVED":"PRESERVED","PROTECTED":"PROTECTED","ERROR":"ERROR","TOTAL":"TOTAL"},
"es":{"title":"Golden Pot v0.1.1 — Comparador de carpetas","subtitle":"Compare dos carpetas de forma segura. La versión 0.1 es de solo lectura.","language":"Idioma","base_folder":"Carpeta base","comparison_folder":"Carpeta de comparación","report_destination":"Destino de los informes","configuration":"Configuración (opcional)","select_folder":"Seleccionar carpeta","select_file":"Seleccionar archivo","analyze":"Analizar carpetas","ready":"Listo. No se modificará ningún archivo.","select_config":"Seleccionar configuración de Golden Pot","json_files":"Archivos JSON","all_files":"Todos los archivos","missing_title":"Falta información","missing_message":"Seleccione las tres carpetas.","analyzing":"Analizando carpetas...","failed":"El análisis falló.","completed":"Análisis completado correctamente.","finished":"Finalizado. Las carpetas originales no fueron modificadas.","json_report":"Informe JSON","text_report":"Informe de texto","ADDED":"AÑADIDOS","UNCHANGED":"SIN CAMBIOS","MODIFIED":"MODIFICADOS","PRESERVED":"CONSERVADOS","PROTECTED":"PROTEGIDOS","ERROR":"ERRORES","TOTAL":"TOTAL"},
"zh":{"title":"Golden Pot v0.1.1 — 文件夹比较器","subtitle":"安全比较任意两个文件夹。0.1 版本为只读模式。","language":"语言","base_folder":"基础文件夹","comparison_folder":"比较文件夹","report_destination":"报告保存位置","configuration":"配置（可选）","select_folder":"选择文件夹","select_file":"选择文件","analyze":"分析文件夹","ready":"准备就绪。不会修改任何文件。","select_config":"选择 Golden Pot 配置","json_files":"JSON 文件","all_files":"所有文件","missing_title":"缺少信息","missing_message":"请选择三个文件夹。","analyzing":"正在分析文件夹...","failed":"分析失败。","completed":"分析成功完成。","finished":"完成。原始文件夹未被修改。","json_report":"JSON 报告","text_report":"文本报告","ADDED":"新增","UNCHANGED":"未更改","MODIFIED":"已修改","PRESERVED":"已保留","PROTECTED":"受保护","ERROR":"错误","TOTAL":"总计"},
"ru":{"title":"Golden Pot v0.1.1 — Сравнение папок","subtitle":"Безопасное сравнение любых двух папок. Версия 0.1 работает только для чтения.","language":"Язык","base_folder":"Базовая папка","comparison_folder":"Папка для сравнения","report_destination":"Папка отчётов","configuration":"Конфигурация (необязательно)","select_folder":"Выбрать папку","select_file":"Выбрать файл","analyze":"Сравнить папки","ready":"Готово. Файлы не будут изменены.","select_config":"Выберите конфигурацию Golden Pot","json_files":"Файлы JSON","all_files":"Все файлы","missing_title":"Недостаточно данных","missing_message":"Выберите все три папки.","analyzing":"Анализ папок...","failed":"Ошибка анализа.","completed":"Анализ успешно завершён.","finished":"Готово. Исходные папки не изменены.","json_report":"Отчёт JSON","text_report":"Текстовый отчёт","ADDED":"ДОБАВЛЕНО","UNCHANGED":"БЕЗ ИЗМЕНЕНИЙ","MODIFIED":"ИЗМЕНЕНО","PRESERVED":"СОХРАНЕНО","PROTECTED":"ЗАЩИЩЕНО","ERROR":"ОШИБКИ","TOTAL":"ВСЕГО"},
"ja":{"title":"Golden Pot v0.1.1 — フォルダー比較","subtitle":"2つのフォルダーを安全に比較します。バージョン0.1は読み取り専用です。","language":"言語","base_folder":"基準フォルダー","comparison_folder":"比較フォルダー","report_destination":"レポート保存先","configuration":"設定（任意）","select_folder":"フォルダーを選択","select_file":"ファイルを選択","analyze":"フォルダーを分析","ready":"準備完了。ファイルは変更されません。","select_config":"Golden Potの設定を選択","json_files":"JSONファイル","all_files":"すべてのファイル","missing_title":"情報が不足しています","missing_message":"3つのフォルダーをすべて選択してください。","analyzing":"フォルダーを分析中...","failed":"分析に失敗しました。","completed":"分析が正常に完了しました。","finished":"完了。元のフォルダーは変更されていません。","json_report":"JSONレポート","text_report":"テキストレポート","ADDED":"追加","UNCHANGED":"変更なし","MODIFIED":"変更済み","PRESERVED":"保持","PROTECTED":"保護","ERROR":"エラー","TOTAL":"合計"}}

def detect_language() -> str:
    code = (locale.getlocale()[0] or "en").split("_")[0].lower()
    return code if code in LANGUAGES else "en"

def translate(language: str, key: str) -> str:
    return TRANSLATIONS.get(language, TRANSLATIONS["en"]).get(key, key)
